name: updateBydszb
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 30 */6 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 检出
        uses: actions/checkout@v4
      - name: 测试网络
        run: curl http://ds.fengcaizb.com/channels/dszb3.gz --output zb3
      - name: 更新内容
        run: |
          # cp migu_video/interface.txt .
          # cp migu_video/playback.xml .
          # rm -rf migu_video
      - name: 推送
        run: |
          # if ! git diff --quiet --exit-code || [ -n "$(git status --porcelain)" ]; then
          #   git config user.name "GitHub Actions"
          #   git config user.email "actions@github.com"
          #   git add .
          #   git commit -m "Update by GitHub Actions"
          #   git push
          # fi
